@startuml


package billing{

class TotalFee

package contract{
class ContractForCharge{
DataMax5GPLan
}

TotalFee -d-> ContractFee
ContractForCharge -u-> ContractFee

}

package discount{
TotalFee -d-> DiscountFee
DiscountService -u-> DiscountFee
DiscountService -d-> ContractForDiscount
}

}

package contractmanage{
interface ContractRepository
ContractRepository -up-> FamilyContracts
ContractRepository -up-> Contract
ContractForCharge -d-> Contract
ContractForDiscount -d-> Contract
DiscountService -d-> FamilyContracts
}

package otherservice{
DiscountService -l-> SmartValueTargetServiceContracts
}

package plan{
Contract -d-> Plan
ContractForCharge -d-> Plan
}

@enduml